services:
  backend:
    image: corqu/igloo-backend:latest
    container_name: igloo-backend
    env_file:
      - .env
    environment:
      AI_SERVICE_BASE_URL: http://igloo-ai-service:8001
    ports:
      - "8080:8080"
    depends_on:
      - ai-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  nginx:
    image: nginx:latest
    container_name: igloo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always

  ai-service:
    image: corqu/igloo-ai-service:latest
    container_name: igloo-ai-service
    env_file:
      - .env
    ports:
      - "8001:8001"
    restart: always

  redis:
    image: redis:latest
    container_name: igloo-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf --requirepass ${Igloo_PROJECT_Redis_Password55}
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    env_file:
      - .env
