services:
  redis:
    image: redis:latest
    container_name: nunchi-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf # 로컬 설정파일을 컨테이너로 연결
      - ./redis-data:/data # 데이터 저장소 연결
    command: redis-server /usr/local/etc/redis/redis.conf # 설정파일을 읽으며 실행하도록 지정
    restart: always
